# Generated by Django 3.1.3 on 2020-11-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(max_length=255)),
                ('title', models.TextField(default='Zawody', max_length=25)),
                ('pic', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_confirmed', models.BooleanField(default=False)),
                ('pcz', models.IntegerField(default=0)),
                ('kczbo', models.IntegerField(default=0)),
                ('kczo', models.IntegerField(default=0)),
                ('pd', models.IntegerField(default=0)),
                ('kd', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('kp', models.IntegerField(default=0)),
                ('kcp', models.IntegerField(default=0)),
                ('pcp', models.IntegerField(default=0)),
                ('char', models.IntegerField(default=0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitors.competitor')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.contest')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='competitors',
            field=models.ManyToManyField(through='tournaments.Result', to='competitors.Competitor'),
        ),
    ]
